accounts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views



app_name="accounts"
urlpatterns = [

    path("login/", views.login_view, name="login"),
    path('cadastro/', views.cadastro_view, name="cadastro"),
    path("logout", views.logout_view, name="logout"),
    path("consulta_email/", views.consulta_email_view, name='consulta_email'),
    #path("solicitar_senha/", views.solicitar_nova_senha, name="solicitar_nova_senha"),
    path("nova_senha/", views.nova_senha, name="nova_senha"),

    path('reset', auth_views.PasswordResetView.as_view(template_name='account/solicitar_senha.html', success_url=reverse_lazy("accounts:password_reset_done")), name="password_reset"),


    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="templates/account/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),


    ]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('lista.urls', namespace='lista'),),
    path("c/", include("accounts.urls", namespace="accounts"),),
    

]

lista/urls.py
from django.urls import path
from . import views
app_name = 'lista'

urlpatterns = [

    path("",  views.index, name='index'),
    path("nova-tarefa/", views.new_tarefa, name='nova-tarefa'),
    path('confirmar/', views.confirmar_item, name='confirmar'),
    path("delete/", views.delete_item, name='delete_item'),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
   ...
   

lista/models.py
from django.db import models
from .utils import send_email
from django.dispatch import receiver
from core import settings
from accounts.models import User
from django.db.models.signals import post_save


class Lista(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.CharField('Novo', max_length=250)
    feito = models.BooleanField(default=False)

    data_criacao = models.DateTimeField(auto_now_add=True)
    data_modificacao =models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Usuário {self.usuario} - {self.item} || status - {self.feito}'

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Itens'

'''@receiver(post_save, sender=User)
def novo_usuario(sender, instance, created, **kwargs):
    if created:
        msg = 'Um novo Usuário foi cadastrado! Verifique no admin do sistema'
        send_email('Novo usuário Cadastrado',msg )



post_save.connect(novo_usuario, sender=settings.AUTH_USER_MODEL)'''

accounts/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
from .models import User
from django.contrib.auth import login as login_j, authenticate
from django.contrib.auth import logout

from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError

def login_view(request):
    template_name = "account/login.html"

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        req = json.load(request)
        email = req["email"]
        senha = req["senha"]

        try:
            user =  User.objects.get(email__iexact=email)
            if user and user.is_active and user.check_password(senha):
                usuario = authenticate(request, username=email, password=senha)
                login_j(request, usuario)
                data = {'logado': True}
                return JsonResponse(data)
            else:
                print('Usuário ou senha invalidos')
                data = {'invalid': True}
                return JsonResponse(data)
        except User.DoesNotExist:
            data = {'invalid': True}
            return JsonResponse(data)

    return render(request, template_name)



def cadastro_view(request):
    template_name = "account/signup.html"

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        sobrenome = "not"
        req = json.load(request)
        email = req["email"]
        senha = req["senha"]
        nome = req["nome"].split(" ")
        if len(nome)>1:
            sobrenome=nome[1]
        print(f"nome {nome} | sobrenome {sobrenome}")
        User.objects.create_user(username=email, email=email, password=senha, first_name=nome[0], last_name=sobrenome)
        usuario = authenticate(request, username=email, password=senha)
        login_j(request, usuario)
        data = {'created': True}
        return JsonResponse(data)

    return render(request, template_name)



def logout_view(request):
    logout(request)
    return redirect('lista:index')


def consulta_email_view(request):

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        try:
            req = json.load(request)
            email = req["email"]
            user = User.objects.get(email__iexact=email)
            if user:
                data = {'exists':True}
                return JsonResponse(data)
        except User.DoesNotExist:
            data = {'exists':False}
            return JsonResponse(data)



def solicitar_nova_senha(request):

    ...
    '''
    template_name = "account/solicitar_senha.html"

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        try:
            req = json.load(request)
            email = req['email']
            user = User.objects.get(email__iexact=email)
            if user:
                assunto = 'Recupere sua senha'
                email_template_name = "account/template_email.txt"

                c = {
                'email' : user.email,
                'dominio' : '127.0.0.1:8000',
                'site_name' : "ToDoListWeb",
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                'user' : user,
                'token' : default_token_generator.make_token(user),
                'protocolo': 'http'
                }
                email = render_to_string(email_template_name, c)

                try:
                    send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                return redirect("accounts:password_reset_complete")

        except User.DoesNotExist:
            data = {'exists' : False}
            return JsonResponse(data)

    return render(request, template_name)
'''

def nova_senha(request):
    template_name = "account/new_senha.html"

    return render(request, template_name)

lista/views.py
from django.shortcuts import render
from .models import Lista
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .utils import send_email

import json

def index(request):

    template_name = 'lista/index.html'
    contexto = {}

    return render (request, template_name, contexto)



@login_required
def new_tarefa(request):
    template_name = 'lista/novo.html'
    item = Lista.objects.filter(usuario=request.user)
    if request.method == 'POST' and request.is_ajax():
        items = json.load(request)
        msg = items['texto']
        iditem = Lista.objects.create(item=msg, usuario=request.user).id

        data = {'msg':msg, 'ok_add': True, 'iditem':iditem}
        return JsonResponse(data)

    tarefas = Lista.objects.filter(usuario=request.user)


    contexto = {'tarefas':tarefas}
    

    return render (request, template_name, contexto)

def confirmar_item(request):
    if request.method == 'POST' and request.is_ajax():
        id_item = json.load(request)['data']

        item = Lista.objects.get(id=id_item)
        if item.usuario == request.user:
            if item.feito:
                item.feito = False
                item.save()
                data = {'item': False}
            else:
                item.feito = True
                item.save()
                data = {'item': True}
        return JsonResponse(data)


def delete_item(request):
    if request.method == 'POST' and request.is_ajax():
        id_item = json.load(request)['data']
        item = Lista.objects.filter(usuario=request.user).filter(id=id_item)
        if item:
            item.delete()
            data = {'deleted':True}
        else:
            data = {'deleted': False}

        return JsonResponse(data)

templates/lista/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel='stylesheet' href="{% static 'css/style.css' %}">
    <link rel='stylesheet' href="{% static 'css/navbar.css' %}">
    <link rel='stylesheet' href="{% static 'css/todo.css' %}">
    <link rel='stylesheet' href="{% static 'css/login.css' %}">
    <link rel='stylesheet' href="{% static 'css/new_senha.css' %}">

      <!-- CSS AlertiFy-->

  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
  <!-- Default theme -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
  <!-- Semantic UI theme -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/semantic.min.css"/>
  <!-- Bootstrap theme -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css"/>
    <!-- Default theme -->

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"/>

    <style>
    {% block css %}
    {% endblock %}
    </style>

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>

    {% include 'lista/navbar.html' %}



    <div class="container main">
      {% block messages %}
      {% endblock %}

    {% block content %}

    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>

    <!--ArletiFy -->
  <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <!-- Fim AlertiFy -->

    <script src="{% static 'js/main.js' %}"></script>


    {% block js %}

    {% endblock %}

  </body>
</html>

templates/lista/index.html
{% extends 'lista/base.html' %}


{% block title %} Home {% endblock %}

{% block content %}

<h3>Inicial</h3>

<iframe sandbox="allow-scripts allow-same-origin" id="67518de3755735" frameborder="0" allowtransparency="true" marginheight="0" marginwidth="0" width="0" hspace="0" vspace="0" height="0" style="height:0px;width:0px;display:none;" scrolling="no" src="https://sync.1rx.io/usersync2/rmpssp?sub=openwrap&amp;gdpr=0&amp;consent=&amp;us_privacy=1---&amp;rurl=https%3A%2F%2Fow.pubmatic.com%2Fsetuid%3Fbidder%3Dunruly%26gdpr%3D0%26gdpr_consent%3D%26uid%3D%24UID">
    </iframe>

{% endblock %}

templates/lista/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a href="{% url 'lista:index' %}" class="navbar-brand">Brand<b class='brand'>Name</b></a>
	<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
		<span class="navbar-toggler-icon"></span>
	</button>
	<!-- Collection of nav links, forms, and other content for toggling -->
	<div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
		<div class="navbar-nav">

			<a href="#" class="nav-item nav-link">Sobre</a>


			<a href="#" class="nav-item nav-link">Contato</a>
		</div>
		{% if user.is_authenticated %}
<ul class="navbar-nav w-100">
	<a href="{% url 'lista:nova-tarefa' %}" id='pulse' class="nav-item nav-link active pulse">Nova tarefa</a>
		<li class="nav-item dropdown ml-auto">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class='boas_vindas'></span>{% if user.first_name %}{{user.first_name}}{% else %}{{user.email}}{% endif %}</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
										<hr>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">Sair</a>
                </div>
            </li>
</ul>
      {% else %}


		<div class="navbar-nav ml-auto action-buttons">
			<div class="nav-item dropdown">
				<a href="{% url 'accounts:login' %}"">Login</a>
          </div>
			</div>


			<div class="nav-item dropdown">
				<a href="{% url 'accounts:cadastro' %}"class="btn btn-primary sign-up-btn">Cadastro</a>


        </div>
        {% endif %}
	</div>
</nav>

templates/lista/novo.html
{% extends 'lista/base.html' %}
{% load static %}
{% block title %}Nova Tarefa {% endblock %}

{% block content %}

<div class="caixa">

<div class="root">

  <input type="text" class="form-control add-task" placeholder="adicionar nova tarefa">
  <!--<button tipe='submit' class='btn-add'>+</button>-->

  <div><button tipe='submit' class='btn btn-success new-btn ml-3'>+</button></div>

</div>

  <div class="fundo">


    {% for tarefa in tarefas %}

    {% if tarefa.feito %}

    <div class="true">
    <div class="id_item" style='display:none;'>{{tarefa.id}}</div>
    <div class="texto"><i class="fas fa-check-circle checked mr-2"></i> {{tarefa.item}} </div>  <i class="fas fa-trash-alt icon"></i>
      </div>



  {% else %}


    <div class="false">
      <div class="id_item" style='display:none;'>{{tarefa.id}}</div>
      <div class="texto"><i class="far fa-circle no-checked mr-2"></i> {{tarefa.item}} </div><i class="fas fa-trash-alt icon"></i>
      </div>




  {% endif %}
  {% endfor %}
</div>
</div>

{% endblock %}


{% block js %}

<script src="{% static 'js/web.js' %}" type="module"></script>

{% endblock %}